theme: jekyll-theme-minimal
logo: IMG_0668.jpeg
title: Po Chiao Chen
show_downloads: true
description: Actively seeking for Data Analyst/Business Analyst Full Time Position | MSBA | R, SQL, Python, Tableau
