theme: jekyll-theme-minimal
logo: IMG_0668.jpeg
title: Po Chiao Chen
show_downloads: true
description: Hi all. 
I am a Master of Science in Business Analytics student at Brandeis and a graduate of the University of Iowa with a bachelor’s degree in accounting and finance. 
I have a long fascination with data, computer language, and modeling. I am proficient in data extraction, data wrangling, data visualization and building machine learning models for prediction with R, Python and SQL. 
